# Generated by Django 5.1.1 on 2024-09-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitChat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
