# Generated by Django 5.1.1 on 2024-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitChat', '0003_textmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
