# Generated by Django 5.0 on 2024-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitChat', '0005_callpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='callpreference',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
